<?php

namespace api\modules\v1\controllers;

use Yii;
use api\modules\v1\controllers\BaseController;
use yii\base\Arrayable;

use yii\filters\auth\CompositeAuth;
use yii\filters\auth\HttpBasicAuth;
use yii\filters\auth\HttpBearerAuth;
use yii\filters\auth\QueryParamAuth;
use common\models\User;
use yii\filters\VerbFilter;
use yii\base\ErrorException;



/**
 * Class CarsController
 * @package api\modules\v1\controllers
 */
class CarsController extends BaseController
{
	/**
	 * @return array
	 * 这里调用前端的数据库user
	 */
	public function behaviors()
	{
		return [
          'basicAuth' => [
              'class' => HttpBasicAuth::className(),
              'auth' => function ($username, $password) {
	              /**
	               * 返回的$user 是一个对象
	               * 目标是直接调用对象的验证密码
	               * 在该对象中 也确实有验证密码的方式
	               */
		                 $user = User::find()->where(['username' => $username])->one();
		                 $password_hash = $user->password_hash;
		                 $rst = Yii::$app->security->validatePassword($password, $password_hash);
		               if ($rst) {
		               	    return $user;
		               }
		               return null;
		             },
                        ],
            ];
	}
	
	
	
	
	
	
	
    public $modelClass = 'api\models\Cars';
	
	
	/**
	 * 禁用响应的方法
	 * 不需要禁用的适合 需要删除对应的方法
	 *
	 * 当前禁用删除的方法
	 */
    public function actions ()
    {
	    $actions = parent::actions(); // TODO: Change the autogenerated stub
	    
	    unset($actions['delete']);
	    
	    return $actions;
    }
	
}





