-- MySQL Script generated by MySQL Workbench
-- 2017年03月27日 星期一 17时31分01秒
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`users` ;

CREATE TABLE IF NOT EXISTS `mydb`.`users` (
  `idusers` INT NOT NULL,
  `userscol` VARCHAR(45) NULL,
  `userscol1` VARCHAR(45) NULL,
  PRIMARY KEY (`idusers`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`table`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`table` ;

CREATE TABLE IF NOT EXISTS `mydb`.`table` (
  `idtable` INT NOT NULL,
  `tablecol` VARCHAR(45) NULL,
  `tablecol1` VARCHAR(45) NULL,
  PRIMARY KEY (`idtable`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`box`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`box` ;

CREATE TABLE IF NOT EXISTS `mydb`.`box` (
  `idbox` INT NOT NULL,
  `boxcol` VARCHAR(45) NULL,
  `boxcol1` VARCHAR(45) NULL,
  `users_idusers` INT NOT NULL,
  `table_idtable` INT NOT NULL,
  PRIMARY KEY (`idbox`),
  INDEX `fk_box_users_idx` (`users_idusers` ASC),
  INDEX `fk_box_table1_idx` (`table_idtable` ASC),
  CONSTRAINT `fk_box_users`
    FOREIGN KEY (`users_idusers`)
    REFERENCES `mydb`.`users` (`idusers`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_box_table1`
    FOREIGN KEY (`table_idtable`)
    REFERENCES `mydb`.`table` (`idtable`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
